services:
  db:
    image: postgres:18.2
    restart: on-failure
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - psql-db:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  psql-db:
    driver: local
